### ISSUE TITLE
Issues running "npm install"

### ISSUE THREAD

**Issue by sidprice** [training4developers/mastering-angular-starter#1]
I am starting the "Mastering Angular, Part 1: Components" course and after getting the repo from GitHub and opening it in VS Code I open a terminal and run "npm install" the following errors occur, claiming Python cannot be found, even though the output below reports Python found and then says it cannot find it:

gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Sid\Python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Sid\Python\python.exe C:\Users\Sid\Python\python.exe
gyp verb check python version `C:\Users\Sid\Python\python.exe -c "import platform; print(platform.python_version());"` returned: "3.6.1\r\n"
gyp verb could not find "C:\Users\Sid\Python\python.exe". checking python launcher
gyp verb could not find "C:\Users\Sid\Python\python.exe". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Sid\Python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\DataRoot\Projects\mastering-angular-starter\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\DataRoot\Projects\mastering-angular-starter\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\DataRoot\Projects\mastering-angular-starter\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\DataRoot\\Projects\\mastering-angular-starter\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "-
-libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\DataRoot\Projects\mastering-angular-starter\node_modules\node-sass
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

Sid

**Comment by ericwgreene** [comment]
Which version of Python do you have installed?

**Comment by sidprice** [comment]
3.6.1

**Comment by sidprice** [comment]
Python Tools for Visual Studio v2.2.6 is also installed
Sid

**Comment by sidprice** [comment]
3.6.1 is what runs from VSCode terminal view.

**Comment by ericwgreene** [comment]
I think NodeGyp requires Python 2.7. Unfortunately, this is not really an Angular issue, its Node.js environment setup issue. I would ensure the Python version which runs from the command line is 2.7. Thanks!

**Comment by sidprice** [comment]
Perfect, thanks Eric, I uninstalled Python 3.6.1 and installed 2.7.13 and the installation completed.
Sid
